package email

import (
	"fmt"
	"log"
	"net/smtp"
	"os"

	"github.com/resend/resend-go/v3"
)

type Sender interface {
	Send(to, subject, body string) error
}

// ConsoleSender writes emails to stdout — used in dev when no real
// provider is configured. Subject and body are plain text.
type ConsoleSender struct{}

func NewConsoleSender() *ConsoleSender {
	return &ConsoleSender{}
}

func (s *ConsoleSender) Send(to, subject, body string) error {
	log.Printf("[EMAIL] To: %s", to)
	log.Printf("[EMAIL] Subject: %s", subject)
	log.Printf("[EMAIL] Body:\n%s\n", body)
	return nil
}

// SMTPSender delivers via standard SMTP (works with any SMTP relay).
type SMTPSender struct {
	host string
	port string
	user string
	pass string
	from string
}

func NewSMTPSender() *SMTPSender {
	return &SMTPSender{
		host: os.Getenv("SMTP_HOST"),
		port: os.Getenv("SMTP_PORT"),
		user: os.Getenv("SMTP_USER"),
		pass: os.Getenv("SMTP_PASS"),
		from: os.Getenv("SMTP_FROM"),
	}
}

func (s *SMTPSender) Send(to, subject, body string) error {
	if s.port == "" {
		s.port = "587"
	}

	msg := []byte(fmt.Sprintf("From: %s\r\nTo: %s\r\nSubject: %s\r\nContent-Type: text/plain; charset=\"utf-8\"\r\n\r\n%s\r\n", s.from, to, subject, body))

	addr := fmt.Sprintf("%s:%s", s.host, s.port)
	auth := smtp.PlainAuth("", s.user, s.pass, s.host)

	return smtp.SendMail(addr, auth, s.from, []string{to}, msg)
}

// ResendSender delivers via the Resend transactional email API.
// Required env vars:
//   - RESEND_API_KEY (e.g. "re_...")
//   - RESEND_FROM    (e.g. "WireHire <noreply@yourdomain.com>" or just "noreply@yourdomain.com")
//
// For testing without configuring a custom domain, Resend's
// `onboarding@resend.dev` test sender works — set:
//   RESEND_FROM=onboarding@resend.dev
type ResendSender struct {
	client *resend.Client
	from   string
}

func NewResendSender() (*ResendSender, error) {
	apiKey := os.Getenv("RESEND_API_KEY")
	if apiKey == "" {
		return nil, fmt.Errorf("RESEND_API_KEY is required for ResendSender")
	}
	from := os.Getenv("RESEND_FROM")
	if from == "" {
		// Resend's shared test sender; only delivers to the account owner.
		from = "onboarding@resend.dev"
	}
	return &ResendSender{
		client: resend.NewClient(apiKey),
		from:   from,
	}, nil
}

// Send delivers a plain-text + HTML multipart email.
//
// The `body` argument is plain text. The HTML version is generated by
// renderHTML() so we get a consistent, readable design without forcing
// every caller to supply HTML.
func (s *ResendSender) Send(to, subject, body string) error {
	html := renderHTML(subject, body)

	params := &resend.SendEmailRequest{
		From: s.from,
		To:   []string{to},
		Subject: subject,
		Text: body,
		Html: html,
	}

	sent, err := s.client.Emails.Send(params)
	if err != nil {
		return fmt.Errorf("resend send: %w", err)
	}
	log.Printf("[EMAIL] Resend: sent id=%s to=%s subject=%q", sent.Id, to, subject)
	return nil
}

// renderHTML wraps the plain-text body in a minimal, brand-neutral
// email template. Kept inline (no CSS framework) for maximum
// compatibility with email clients.
func renderHTML(subject, body string) string {
	// Very small HTML escaper — sufficient for the URL/text bodies we
	// generate (the plain text already contains the full URL, no user
	// HTML is interpolated).
	esc := func(s string) string {
		out := make([]rune, 0, len(s))
		for _, r := range s {
			switch r {
			case '<':
				out = append(out, []rune("&lt;")...)
			case '>':
				out = append(out, []rune("&gt;")...)
			case '&':
				out = append(out, []rune("&amp;")...)
			case '"':
				out = append(out, []rune("&quot;")...)
			default:
				out = append(out, r)
			}
		}
		return string(out)
	}
	// Naive paragraph split on double newline.
	body = esc(body)
	var paras []string
	for _, p := range splitParagraphs(body) {
		paras = append(paras, "<p style=\"margin:0 0 16px 0;font-size:15px;line-height:24px;color:#334155;\">"+p+"</p>")
	}
	return fmt.Sprintf(`<!doctype html>
<html><body style="margin:0;padding:0;background:#f8fafc;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,'Helvetica Neue',Arial,sans-serif;color:#0f172a;">
  <table role="presentation" width="100%%" cellpadding="0" cellspacing="0" style="background:#f8fafc;padding:32px 0;">
    <tr><td align="center">
      <table role="presentation" width="560" cellpadding="0" cellspacing="0" style="background:#ffffff;border:1px solid #e2e8f0;border-radius:8px;padding:32px;">
        <tr><td>
          <h1 style="margin:0 0 24px 0;font-size:18px;font-weight:600;color:#0f172a;">%s</h1>
          %s
          <p style="margin:24px 0 0 0;font-size:12px;color:#94a3b8;">WireHire</p>
        </td></tr>
      </table>
    </td></tr>
  </table>
</body></html>`, esc(subject), joinStrings(paras))
}

func splitParagraphs(s string) []string {
	out := []string{}
	cur := ""
	for _, r := range s {
		if r == '\n' && len(cur) > 0 && cur[len(cur)-1] == '\n' {
			if cur != "" {
				out = append(out, cur[:len(cur)-1])
			}
			cur = ""
			continue
		}
		cur += string(r)
	}
	if cur != "" {
		out = append(out, cur)
	}
	return out
}

func joinStrings(ss []string) string {
	out := ""
	for _, s := range ss {
		out += s
	}
	return out
}

// BuildVerifyEmail returns (subject, plain-text body) for the
// account verification email.
func BuildVerifyEmail(verifyURL string) (subject, body string) {
	return "Verify your email",
		fmt.Sprintf(`Welcome to WireHire!

Please verify your email by clicking the link below:

%s

This link expires in 24 hours. If you did not create this account, you can safely ignore this email.`, verifyURL)
}

// BuildResetEmail returns (subject, plain-text body) for the
// password reset email.
func BuildResetEmail(resetURL string) (subject, body string) {
	return "Reset your WireHire password",
		fmt.Sprintf(`You (or someone using your email) requested a password reset for your WireHire account.

Click the link below to choose a new password:

%s

This link expires in 1 hour. If you did not request this, you can safely ignore this email — your password will not change.`, resetURL)
}
